
cc.Class({
    extends: cc.Component,

    properties: {
        skinSkeleton: sp.Skeleton,
        summaryLabel: cc.Label,
        nameLabel: cc.RichText,
        iconSripte: cc.Sprite,
    },


    onLoad() { },

    bind(jobInfo) {
        // skinSkeleton.skeletonData = 
        this.nameLabel.string = '<outline color=#ffffff width=2><b>' + jobInfo.name + '</b></outline>';
        this.summaryLabel.string = jobInfo.msg;

        // cc.loader.loadRes(secondIcon, cc.SpriteFrame, (error, spriteFrame) => {
        //     this.iconSripte.spriteFrame = spriteFrame;
        // });

    },

    start() {

    },

    // update (dt) {},
});
